ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"


USER root

#install golang

ENV GOLANG_VERSION 1.12.6

RUN set -eux; \
	\
# this "case" statement is generated via "update.sh"
	dpkgArch="$(dpkg --print-architecture)"; \
	\
	url="https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz"; \
	wget -O go.tgz "$url"; \
	tar -C /usr/local -xzf go.tgz; \
	rm go.tgz; \
	\
	export PATH="/usr/local/go/bin:$PATH"; \
	go version

ENV GOPATH /go

ARG CLOUD_SDK_VERSION=252.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION

ENV PATH "$PATH:/opt/google-cloud-sdk/bin/:$GOPATH/bin:/usr/local/go/bin"


RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"


# Install dependencies 
RUN apt-get update && apt-get install -y --no-install-recommends \
                openssh-client \
		g++ \
                apt-transport-https \
                lsb-release \
		gcc \
		libc6-dev \
		make \
		pkg-config \
                vim \
                libzmq3-dev \
                gnupg2 \
                curl \
                iputils-ping \
                dnsutils \
    && \
    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" > /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update && apt-get install -y google-cloud-sdk=${CLOUD_SDK_VERSION}-0 kubectl  && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    gcloud config set metrics/environment github_docker_image && \
    gcloud --version


# Install kubectl 
#RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
# && chmod +x kubectl \
# && mv kubectl /usr/local/bin/kubectl

# Install bosh
RUN curl -Lo bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v5.5.1/bosh-cli-5.5.1-linux-amd64 \
  && chmod +x bosh \
  && mv bosh /usr/local/bin

# install gophernotes
RUN go get github.com/gopherdata/gophernotes \
    && cp /go/bin/gophernotes /usr/local/bin/ \
    && mkdir -p ~/.local/share/jupyter/kernels/gophernotes \
    && cp -r /go/src/github.com/gopherdata/gophernotes/kernel/* ~/.local/share/jupyter/kernels/gophernotes 

RUN chown -R ${NB_USER} ${HOME} $GOPATH 
USER ${NB_USER}
WORKDIR ${HOME}

# install bash kernel
RUN pip install bash_kernel && python -m bash_kernel.install

# install nbgitpuller
RUN pip install nbgitpuller

